### ISSUE TITLE
Linkie integration

### ISSUE THREAD

**Issue by LordMZTE** [QuiltMC/cozy-discord#1]
What about commands semilar to those from the [linkie bot](https://github.com/linkie/linkie-discord) to look up mappings?

**Comment by gdude2002** [comment]
Quilt doesn't have any mappings at the moment.

When everything's set up, we'll consider looking into this - however, Quilt's mappings are likely going to need something more complex than what Linkie provides, we'll have to see.

If we do decide to go this route, I've [already written an extension](https://github.com/Kord-Extensions/ext-mappings/).

**Comment by gdude2002** [comment]
Somehow I forgot to close this one when I added the above-linked mappings extension. But, yeah, that's done.

QM still isn't supported this way, and probably won't be for some time, but we'll work on that when we can.
