### ISSUE TITLE
Thread Persistence Command

### ISSUE THREAD

**Issue by gdude2002** [QuiltMC/cozy-discord#18]
Simple enough: A command that marks a thread as "should not archive", and unarchives it whenever that happens - unless a staff member archives it with `/thread archive`. Can probably just modify the existing threads collection for this.

**Comment by Jamalam360** [comment]
I've done something like this before, I'm happy to try and work on this gdude?

**Comment by gdude2002** [comment]
@Jamalam360 Yup, you're quite welcome to if you'd like!

**Comment by gdude2002** [comment]
Some possible enhancements:

* Logging to the cozy-logs channel when someone does set a thread to stay open
* A command to change the thread owner when needed
