### ISSUE TITLE
Move the last remaining `?` command to a slash command 

### ISSUE THREAD

**Issue by triphora** [QuiltMC/cozy-discord#29]
![image](https://user-images.githubusercontent.com/60205699/148288362-be1a1aba-9b81-4d73-9d5e-8604b08dce2b.png)
Currently, there are still the `?help` and `?sync bans` commands. The help command no longer has a reason to exist with the slash command info being given when you just type `/`. Thus, the help command should be removed, and the ban sync command moved to a slash command. (Also, change the `Cozy [?]` bot name accordingly).

**Comment by gdude2002** [comment]
I did the thing
