### ISSUE TITLE
Relicensing: MPL

### ISSUE THREAD

**Issue by gdude2002** [QuiltMC/cozy-discord#31]
Because of the changes proposed in #17, I think it's worth moving to a weak copyleft licence. The [Mozilla Public License (2.0)](https://www.mozilla.org/en-US/MPL/) is what Kord Extensions (the Framework Cozy uses) is written under, so I'm relatively familiar with it.

This licence change would largely only affect contributors and people that use forks of this repository. It would require anyone distributing modified source code to retain the MPL licence and attribution, and anyone who distributes binary copies to make their modified source available and link to it (or link to this repo if they aren't modifying it). 

The licence change would not affect private use, and anyone developing a bot using Cozy modules as provided would not need to do anything. 

---

Cozy is currently licensed under the Creative Commons Zero licence. This is a public domain dedication, which means that we don't technically need to seek permission to change the licence. That said, I would _much_ rather gather that permission from our contributors regardless, in the interests of transparency and good faith interaction.

For that reason, I'll need that confirmation from the following people:

- [x] @gdude2002 
- [x] @Jamalam360 
- [x] @Scotsguy 
- [x] @Southpaw1496 
- [x] @TheGlitch76

The following people are not contributors, but I'm aware that they may have projects that fork or otherwise use code from this project. For that reason, I'd also like to request their permission:

- [x] @doctor4t
- [x] @NoComment1105
- [x] @Pyrofab
- [x] @sschr15

If you're happy with this licensing change, please leave a comment to that effect below.

**Comment by Jamalam360** [comment]
I'm happy with the change :+1:

**Comment by sschr15** [comment]
@Pyrofab and @doctor4t may also want to discuss since my fork is for Ladysnake more generally, but I personally am fine with switching to MPL.

**Comment by doctor4t** [comment]
All good for me

**Comment by TheGlitch76** [comment]
I am fine with the licensing change to MPL.

**Comment by Scotsguy** [comment]
Fine by me.

**Comment by Pyrofab** [comment]
Works for me

**Comment by NoComment1105** [comment]
Sounds good. 👍🏼

**Comment by Southpaw1496** [comment]
I'm happy with the change.

**Comment by gdude2002** [comment]
Aaand that's everyone!

Thanks for this, I'll get that sorted out soon, and I'll close this issue when it's done.
