### ISSUE TITLE
Mojira issue watcher

### ISSUE THREAD

**Issue by LambdAurora** [QuiltMC/cozy-discord#33]
For following specific mojira issues and be aware of their state changes.

**Comment by gdude2002** [comment]
This is a good idea, but I don't have time to look into how it'd be implemented. Anyone have any ideas?

**Comment by Southpaw1496** [comment]
I have found Atlassian's official [Jira Rest Java Client](https://bitbucket.org/atlassian/jira-rest-java-client/src/master/) as well as [Jira Klient](https://github.com/routis/jira-klient) (Kotlin implementation), and some [Jira Rest API docs](https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/). I also found the source for the official [Mojira Discord Bot](https://github.com/mojira/mojira-discord-bot) which could be helpful.

I still haven't worked out if we can actually access the API without authorization, however.

**Comment by skyrising** [comment]
> I still haven't worked out if we can actually access the API without authorization, however.

As far as I know it's not possible, you need an account.

**Comment by Southpaw1496** [comment]
Seems you can also query XML, for example https://bugs.mojang.com/si/jira.issueviews:issue-xml/MC-5/MC-5.xml

**Comment by Southpaw1496** [comment]
Also, it does look like you can use a lot of the standard REST API without auth (for example, https://bugs.mojang.com/rest/api/latest/issue/MC-5)
