### ISSUE TITLE
Showcase: PluralKit integration 

### ISSUE THREAD

**Issue by Akarys42** [QuiltMC/cozy-discord#42]
# Abstract

Currently, when a user using PluralKit posts a message in the #gallery channel, a thread is created on the user message, which is then deleted, making the thread unaccessible. We should account for it.

# Specification

When a user post a message, the bot should wait up to one or two seconds to see if the message gets deleted. If so, the PluralKit API should be called. If the message correctly resolves, the thread should be created, with ownership granted to the user account.

**Comment by Gaming32** [comment]
I looked into stuff like this at one point. PK offers an API that would likely be really useful here.

**Comment by gdude2002** [comment]
We already use the PK API, and a wrapper is provided with Cozy.

This approach does not go far enough for our use-cases. We need specific events for PK messages with extra detail.
