### ISSUE TITLE
Feature request: Log analysis in DMs?

### ISSUE THREAD

**Issue by Ampflower** [QuiltMC/cozy-discord#54]
## Why?

Cozy is capable of analysing logs in the support channel in Quilt, and some just send logs there for getting its automatic analysis of what's going wrong. Allowing it to be DM'd could be useful for those who uses the automatic analysis for their own use rather than to get support.

**Comment by Jamalam360** [comment]
This can be closed, it works in DMs

**Comment by Ampflower** [comment]
Yes, yes it does.
