### ISSUE TITLE
[Feature request] Self timeout with removal of verified role/viewing permissions.

### ISSUE THREAD

**Issue by TheArcaneBrony** [QuiltMC/cozy-discord#72]
Dear Quilt staff,

I would like to request to be able to do a self-timeout that also revokes our ability to see channel contents.

We're currently taking a break from Quilt due to mental health, and thus would like to be able to revoke our ability to see messages as to not have a reason to interact, without having to fully leave the guild.

This could maybe be implemented as an additional optional argument?

Regards,
Rory&

**Comment by Akarys42** [comment]
The suggestion [quarantine command](https://discord.com/channels/817576132726620200/1080011154673389578/1080011158922207273) already exists for this problem. Ideally, discussions should happen there first, then move to a Github issue if approved.

**Comment by TheArcaneBrony** [comment]
You can't send messages when timed out...

Either way, I made the suggestion in modmail and was told to make an issue instead.

**Comment by Akarys42** [comment]
Closing for now to centralize discussions in the suggestion
