### ISSUE TITLE
move mod incompatibility list to github

### ISSUE THREAD

**Issue by eristhea** [QuiltMC/cozy-discord#74]
the mod incompatibility list should be somewhere other than the forum, for two reasons
- it's bothersome to submit an update, since only a few people have permission to make edits
- it complicates parsing

I propose we host it on github, so update can simply be done through pull requests. I think a dedicated repository for this file would be best, so parity issues with the forum could be tracked through github issues.

**Comment by Southpaw1496** [comment]
As an alternative, we can also host it on the website, and we would still be able to update it through pull requests. We can create a new issue tag for incompatibility updates if necessary, but we can probably also just track it through the forum thread, as it is now, and make submitting a post on the forum thread a requirement for the pull request to be merged.

**Comment by eristhea** [comment]
mhm, the website repository would be good too! as long as there's a better way to update it than "ping gdude" I'm happy

**Comment by gdude2002** [comment]
I'd also vouch for putting it on the site.

**Comment by Southpaw1496** [comment]
I have submitted a Pull Request to the website (https://github.com/QuiltMC/quiltmc.org/pull/147) which can be merged once the changes required for Cozy are implemented.
